### ISSUE TITLE
Inline size classes not picked up by cribsheet

### ISSUE THREAD

**Issue by colepeters** [enhance-dev/arc-plugin-enhance-styles-cheatsheet#1]
Inline size classes (`.si-*`) aren't getting picked up by the cribsheet:

<img width="696" alt="image" src="https://github.com/enhance-dev/enhance-styles-cribsheet/assets/1713932/c059b8e9-7d1c-45ee-80de-25b6c1b59972">

**Comment by kristoferjoseph** [comment]
This was due to a newline in the sizes output.
Fixed in `@enhance/styles` v5.0.5

**Comment by kristoferjoseph** [comment]
Fixed in `v0.0.9`
